name: Update dbdocs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      - name: Verify dbdocs installation
        run: dbdocs --version

      - name: Update dbdocs project
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: dbdocs build ./schema.dbml --project vinyl_shop
